name: CI

on:
  push:
    branches: [dev,main]
  pull_request:
    branches: [dev,main]

env:
  MIX_ENV: test

jobs:
  deps: [...]
  
  static_code_analysis: [...]
  
  unit_tests:
    name: Unit Tests
    needs: deps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir: [1.11]
        otp: [23.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Run test
        run: mix test --slowest 10